Repository Anupkjha2601/food-recipes-website, pull requests merged in 2023-08, with the labels that each got.

#620 distorted icons fixed
  services.html
Labels: level1, gssoc23

#625 gallery page beautified
  css/lightGallery.css
  gallery.html
Labels: level2, gssoc23

#649 feat: add issue template for refactoring codebase ⚒️ ✨
  .github/workflows/ISSUE_TEMPLATE/refactor.yml
Labels: gssoc23, level3

#651 feat: add issue template for bug ⚒️✨
  .github/workflows/ISSUE_TEMPLATE/bug-report.yml
Labels: level2, gssoc23

#650 feat: revamp feature request issue template ⚒️✨
  .github/workflows/ISSUE_TEMPLATE/feature_request.yml
Labels: gssoc23

#666 Update README.md
  README.md
Labels: level2, gssoc23

#671 fix: contact page navbar improvement
  contact.html
  css/style.css
Labels: level2, gssoc23

#674 Added GitHub link in footer.
  index.html
Labels: level2, gssoc23

#680 feat: add gssoc banner to repository documentation 📝✨
  README.md
Labels: level2, gssoc23

#681 Added Hover Animation to the Cards in Services
  css/style.css
Labels: gssoc23, level3

#686 contact page issue solved with reformat document
  contact.html
Labels: level2, gssoc23

#687 removed bottom scroll bar and gird converted in horizontal
  css/style.css
  index.html
Labels: level2, gssoc23

#691 feat: hover effects for icons with revamping on icons page 🪄✨
  css/style.css
Labels: level2, gssoc23

#697 docs: make gssoc banner adaptive to github dark/light mode 💫✨
  README.md
Labels: level2, gssoc23

#699 Removed bug from testimonial section
  css/flexslider.css
  css/style.css
  index.html
Labels: level1, gssoc23

#703 Changed images from png to webp
  icons.html
  services.html
  typography.html
Labels: level1, gssoc23

#711 menu list revamped
  css/style.css
Labels: level2, gssoc23

#718 About page revamp
  about.html
  css/style.css
Labels: level2, gssoc23

#714 feat: GitHub workflow which Lock the Chat until the gssoc23 is not added.
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/documentation.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/project-request.md
  .github/ISSUE_TEMPLATE/refactor.yml
  .github/workflows/lock.yml
Labels: gssoc23, level3

#692 fix: Added ARIA Attributes to Form Section existed in Contact Us Page
  contact.html
Labels: gssoc23, level3

#721 Menu part of about page revamped
  about.html
  css/style.css
Labels: level2, gssoc23

#720 added greeting workflow
  .github/workflows/greetings.yml
Labels: level2, gssoc23

#724 Update README.md
  README.md
Labels: level2, gssoc23

#725 feat: Added the social media icons feature
  icons.html
Labels: level2, gssoc23

#726 feat: improve collabration by adding auto comment feature 🚀🔥
  .github/workflows/auto-comment-newly-opened-pr.yml
  .github/workflows/auto-comment-on-new-issues.yml
  .github/workflows/greetings.yml
  .github/workflows/lock-newly-created-issues.yml
Labels: gssoc23, level3

#727 Redesigned the Image in the Homepage and added hover effect to boxes
  css/style.css
Labels: level2, gssoc23

#728 gallery title added
  gallery.html
Labels: level2, gssoc23

#730 feat: copying icons to clipboard feature 🚀🔥
  icons.html
Labels: level2, gssoc23

#735 Removed redundant code from code base #734
  contact.html
Labels: level2, gssoc23

#737 Hover effect improved by adding padding
  css/style.css
  services.html
Labels: level2, gssoc23

#743 Changed Some Images nad made some changes in css
  404.html
  css/style.css
  images/404.png
Labels: level2, gssoc23

#739 refactor: revamp the design of google translator button for all pages 🪄✨
  about.html
  contact.html
  css/style.css
  css/translate.css
  gallery.html
  icons.html
  index.html
  services.html
  typography.html
Labels: gssoc23, level3

#738 Style upper services page
  css/style.css
  services.html
Labels: level2, gssoc23

#748 Added/Fixed Footer Social Button Hovering Effects
  css/style.css
Labels: level2, gssoc23

#760 Added Contributors list
  contributor.html
  css/contributors.css
  index.html
  js/contributor.js
Labels: gssoc23, level3

#766 fixed icons in our chef's section.
  index.html
Labels: level2, gssoc23

#770 Update style.css
  css/style.css
Labels: level2, gssoc23

#775 Services section beautified
  css/style.css
  services.html
Labels: level2, gssoc23

#774 text updated
  css/style.css
Labels: level1, gssoc23

#655 modifiedchanges
  about.html
  css/style.css
  css/style3.css
  index.html
Labels: level2, gssoc23

#779 favicon fixed
  contributor.html
Labels: level2, gssoc23

#781 #746 Resolved
  css/style.css
  css/translate.css
  index.html
Labels: level2, gssoc23

#783 Styled scroll to top button. ✨
  css/style.css
  images/top.webp
Labels: level2, gssoc23

#784 docs: replace plaintext into attractive tech stack badges 🪄✨
  README.md
Labels: level2, gssoc23

#793 Scroll bar modified and Horizontal scroll removed
  css/style.css
  css/style2.css
  css/style3.css
Labels: level2, gssoc23

#811 fix: Corrected the project name in issue template
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: level1, gssoc23

#807 Added Receipe Bot :Receipe Rover
  gallery.html
  index.html
  services.html
Labels: gssoc23, level3

#806 Added hover effect to the instagram post
  css/style.css
  index.html
Labels: level2, gssoc23

#805 contact form wrap
  contact.html
  css/style.css
Labels: level2, gssoc23

#798 contributor navbar added
  contributor.html
Labels: level2, gssoc23

#797 glyphicons hover revamped
  css/style.css
  icons.html
Labels: level2, gssoc23

#788 Fixed Navbar and Added a Design to it
  css/style.css
  index.html
Labels: level2, gssoc23

#812 Removed Multiple Cards in Services & Highlighted Services when in the page
  services.html
Labels: level2, gssoc23

#813 Contributor page issue resolved
  css/contributors.css
  js/contributor.js
Labels: level2, gssoc23

#789 Gallery page search bar text is conflict to the icon
  about.html
  contact.html
  contributor.html
  gallery.html
  index.html
  services.html
Labels: level2, gssoc23

#815 Styled main page
  css/style.css
  index.html
Labels: level2, gssoc23

#817 Added PWA to food-recipes-website
  icon-192x192.png
  icon-256x256.png
  icon-384x384.png
  icon-512x512.png
  index.html
  manifest.json
  serviceWorker.js
Labels: gssoc23, level3

#790 #352 Resolved
  about.html
  contact.html
  css/style.css
  gallery.html
  icons.html
  images/bottomButton.webp
  index.html
  js/scrollToBottom.js
  services.html
  typography.html
Labels: level2, gssoc23

#786 feat: enhance gallery cards by adding unique dish names and description ☕✨
  css/style.css
  gallery.html
Labels: level2, gssoc23

#818 Added a Copy clipboard in social-media icons
  icons.html
Labels: level2, gssoc23

#822 Added box shadow to the contact page
  css/style.css
Labels: level1, gssoc23

#823 Added additional effects like box shadow to the page components
  css/style.css
Labels: level2, gssoc23

#824 Added improved hover and box shadow
  css/lightGallery.css
Labels: level1, gssoc23

#825 Added box shadow to maon page cards
  css/style.css
Labels: level1, gssoc23

#826 added github workflow for greerting
  .github/workflows/greeting.yml
Labels: level1, gssoc23

#782 feat: add animations for entire Food Recipes Website 🚀🔥
  about.html
  contact.html
  css/aos.css
  gallery.html
  icons.html
  index.html
  js/aos.js
  js/scrollReveal.js
  services.html
  signup.html
  typography.html
Labels: gssoc23, level3

#829 Select button UI added
  css/style.css
  index.html
Labels: level2, gssoc23
