Repository Anupkjha2601/food-recipes-website, pull requests merged in 2023-06, with the labels that each got.

#42 Update scroll link to navigate to about.html
  index.html
Labels: level2, gssoc23

#135 `Mail` link in `footer` is now clickable
  about.html
  gallery.html
  icons.html
  index.html
  services.html
  typography.html
Labels: level2, gssoc23

#169 Updated trademark in index.html (#20)
  index.html
Labels: level2, gssoc23

#29 Top to scroll button
  index.html
Labels: gssoc23

#180 Scroll to top button added
  css/style.css
  index.html
  js/scrolltoTop.js
Labels: level2, gssoc23

#171 favicon added issue #44
  about.html
  contact.html
  gallery.html
  icons.html
  index.html
  services.html
  typography.html
Labels: level2, gssoc23

#300 Contact page updated
  contact.html
  css/style.css
Labels: gssoc23, level3

#257 Updated Alignment of Website's Headings
  css/style.css
  index.html
Labels: level1, gssoc23

#176 Update README.md
  README.md
Labels: gssoc23, level3

#262 📝 [DOCS]: ADD PROJECT PREVIEW IMAGE & MINOR CHANGES
  README.md
  images/preview.webp
Labels: gssoc23, level3

#172 adding cursor to pointer property on images of todays special section
  css/style.css
Labels: level2, gssoc23

#336 Issue No. #306 Missing Meta Description on Website Solved.
  index.html
Labels: level2, gssoc23

#185 Adding line Height
  css/style.css
Labels: gssoc23

#187 Update README.md of the repo #36
  README.md
Labels: gssoc23, level3

#210 contact button alignment done correct
  css/style.css
Labels: gssoc23

#239 Improved Scroll-to-top arrow
  css/style.css
  images/white-arrow-icon-png-26.jpg
  js/move-top.js
Labels: level2, gssoc23

#254 Adding blog on pasta in Our Food blog section
  services.html
Labels: level2, gssoc23

#182 Set loader on each page
  .vscode/settings.json
  about.html
  contact.html
  css/style.css
  gallery.html
  icons.html
  index.html
  js/script.js
  services.html
  typography.html
Labels: gssoc23

#255 Changed the style of search button in galary and a new feature is added for the INPUT field
  css/lightGallery.css
  css/owl.carousel.css
  css/style.css
  gallery.html
  index.html
  js/lightGallery.js
Labels: level2, gssoc23

#223 Adds contributing.md file
  CONTRIBUTING.md
Labels: level1, gssoc23

#289 Added `Chatbot`
  chatBot/script.js
  chatBot/style.css
  images/pngegg(2).png
  index.html
Labels: gssoc23, level3

#328 Add cursor pointer property to images in today specials section
  index.html
Labels: level2, gssoc23

#251 Testimonial Section updated.
  css/style.css
  index.html
Labels: level2, gssoc23

#379 Grammar correction
  services.html
Labels: level1, gssoc23

#390 Redesign the search button in gallery section
  css/style.css
  gallery.html
Labels: level1, gssoc23

#394 Update services.html title issue #45
  services.html
Labels: level1, gssoc23

#403 Fixed Alignment `Major issue`
  css/style.css
  index.html
Labels: level2, gssoc23

#402 Scrollbar
  chatBot/style.css
  index.html
Labels: level2, gssoc23

#374 Added target attribute in footer socials
  about.html
  contact.html
  gallery.html
  icons.html
  index.html
  services.html
  signup.html
  typography.html
Labels: gssoc23

#265 you can clearly able to see Opening timings , address , recent posts
  css/style.css
  index.html
Labels: level2, gssoc23

#334 newsletter section modified
  css/style.css
  images/newsletter.png
  index.html
Labels: level2, gssoc23

#358 added functionality to the scroll to bottom button
  index.html
Labels: level2, gssoc23

#389 UI issues were resolved
  about.html
  contact.html
  css/carousel.css
  css/lightGallery.css
  css/style.css
  gallery.html
  icons.html
  index.html
  services.html
  signup.html
  typography.html
Labels: level2, gssoc23

#406 README.md Upgraded
  README.md
Labels: level2, gssoc23

#413 added issue and pull template
  .github/workflows/ISSUE_TEMPLATE/bug-report.md
  .github/workflows/ISSUE_TEMPLATE/project-request.md
  .github/workflows/ISSUE_TEMPLATE/update-request.md
  .github/workflows/pull_request_template.md
Labels: gssoc23, level3

#244 Solved Email displaying issue
  about.html
  contact.html
  gallery.html
  icons.html
  index.html
  services.html
  typography.html
Labels: level1, gssoc23

#423 Added `openAI-GPT` in ChatBot
  chatBot/script.js
  chatBot/style.css
  css/style.css
  index.html
Labels: gssoc23, level3

#436 Upadate Contributing.md file
  contributing.md
Labels: level2, gssoc23

#432 back to top button ui improved and animated with box shadow on hover #431
  css/style.css
Labels: level2, gssoc23
