Repository Anupkjha2601/food-recipes-website, pull requests merged in 2023-07, with the labels that each got.

#350 Issue No. #307 [FIXED] In the footer section of the site, the copyright year should be dynamically generated instead of being statically hardcoded.
  about.html
  contact.html
  gallery.html
  icons.html
  index.html
  js/copyrightYear.js
  services.html
  typography.html
Labels: level1, gssoc23

#442 Update README.md
  README.md
Labels: level2, gssoc23

#464 added Code of conduct
  CODE_OF_CONDUCT.md
Labels: level2, gssoc23

#487 changes are done accordingly
  .github/workflows/azure-static-web-apps-ashy-sand-06af1b40f.yml
  .github/workflows/azure-static-web-apps-yellow-bay-03a907f10.yml
  CONTRIBUTING.md
  README.md
  about.html
  contact.html
  css/style.css
  gallery.html
  icons.html
  index.html
  js/lightGallery.js
  services.html
  typography.html
Labels: level2, gssoc23

#494 Contact page design
  contact.html
  css/style.css
Labels: level2, gssoc23

#579 2 search bar issue resolved
  about.html
  contact.html
  css/style.css
  gallery.html
  icons.html
  index.html
  services.html
  signup.html
  typography.html
Labels: level1, gssoc23

#580 Orientation resolved
  gallery.html
Labels: level1, gssoc23

#573 Created Issues Template frome scratch
  .github/workflows/ISSUE_TEMPLATE/bug-report.md
  .github/workflows/ISSUE_TEMPLATE/bug-report.yml
  .github/workflows/ISSUE_TEMPLATE/documentation.yml
  .github/workflows/ISSUE_TEMPLATE/feature_request.yml
  .github/workflows/ISSUE_TEMPLATE/update-request.md
Labels: level2, gssoc23

#562 Add Strong Tag to Footer Section and font color change
  services.html
Labels: level2, gssoc23

#586 ToTop button change
  .DS_Store
  css/style.css
Labels: level1, gssoc23

#496 added a preloader
  contributing.md
  css/style.css
  index.html
  package-lock.json
Labels: gssoc23, level3

#604 feat: made social anchors accessible for entire food recipes website 🚀
  about.html
  contact.html
  gallery.html
  icons.html
  index.html
  services.html
  typography.html
Labels: level2, gssoc23

#615 feat: improve seo for all pages on food recipes website 🚀 ✨
  about.html
  contact.html
  gallery.html
  icons.html
  index.html
  services.html
  signup.html
  typography.html
Labels: gssoc23

#617 search box fixed
  gallery.html
Labels: level1, gssoc23

#647 update footer section #646
  contact.html
  gallery.html
  index.html
Labels: level2, gssoc23

#643 docs: fix broken documentation 📝🛠️
  README.md
Labels: level2, gssoc23

#642 minor css changes [Days of week now visible under "Open Timings"] Issue #608
  about.html
  contact.html
  css/style.css
  gallery.html
  icons.html
  index.html
  services.html
  typography.html
Labels: level2, gssoc23
